export const COLLECT_WINDOW = 'COLLECT_WINDOW'
export const CREATE_NOTE_WINDOW = 'CREATE_NOTE_WINDOW'
export const SUBOPTIONS_MANAGE_WINDOW = 'SUBOPTIONS_MANAGE_WINDOW'
export const SETTING_WINDOW = 'SETTING_WINDOW'
export const MAIN_WINDOW = 'MAIN_WINDOW'
export const ADD_FRIENDS_AND_GROUP_WINDOW = 'ADD_FRIENDS_AND_GROUP_WINDOW'
export const LOGIN_WINDOW = 'LOGIN_WINDOW'
// export enum WindowsType {
//     COLLECT_WINDOW,
//     CREATE_NOTE_WINDOW,
//     SUBOPTIONS_MANAGE_WINDOW,
//     SETTING_WINDOW,
//     MAIN_WINDOW
// }