/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppOperate: typeof import('./src/components/AppOperate/index.vue')['default']
    EditPage: typeof import('./src/components/UserInfoMiniCard/components/EditPage/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPan: typeof import('element-plus/es')['ElTabPan']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpdate: typeof import('element-plus/es')['ElUpdate']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InfoBlock: typeof import('./src/components/InfoBlock/index.vue')['default']
    InfoBlock2: typeof import('./src/components/InfoBlock2/index.vue')['default']
    LeftSubOptions: typeof import('./src/components/LeftSubOptions/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SettingOptions: typeof import('./src/components/SettingOptions/index.vue')['default']
    SubIconsManage: typeof import('./src/components/LeftSubOptions/components/SubIconsManage/index.vue')['default']
    SubOptionsItemsCard: typeof import('./src/components/LeftSubOptions/components/SubOptionsManage/components/SubOptionsItemsCard/index.vue')['default']
    SubOptionsManage: typeof import('./src/components/LeftSubOptions/components/SubOptionsManage/index.vue')['default']
    TextMessage: typeof import('./src/components/MessageBubble/TextMessage/index.vue')['default']
    UserInfoMiniCard: typeof import('./src/components/UserInfoMiniCard/index.vue')['default']
  }
}
